import React, { useState } from 'react';
import type { Laptop, LaptopVariantConfig, RmbPricingSettings } from '../../shared/types';
import { cpuLabel, emptyLaptopVariants } from '../../shared/laptopVariants';
import { isPreorderLaptop, laptopDeliveries } from '../../shared/rmbPricing';
import { formatPesewas, cedisToPesewas } from '../../shared/money';
import { LaptopVariantChip } from '../components/LaptopVariantChip';
import { RmbCostEditor, rmbDeliveryLabel } from './RmbCostEditor';

const input = 'w-full min-w-0 rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm';
const button = 'rounded-xl border border-slate-300 bg-white px-3 py-2 text-xs font-bold text-[#014040]';
export function LaptopVariantsToggle({ laptop, onChange }: { laptop: Laptop; onChange: (laptop: Laptop) => void }) {
  return <label className="flex items-center gap-3 rounded-xl border bg-[#f8fbfa] p-3 font-bold text-[#014040] sm:col-span-2 xl:col-span-3"><input type="checkbox" className="h-4 w-4 accent-[#014040]" checked={!!laptop.variantsEnabled} onChange={event => onChange({ ...laptop, variantsEnabled: event.target.checked, variantConfig: laptop.variantConfig || emptyLaptopVariants() })} />Variants <span className="text-xs font-normal">{laptop.variantsEnabled ? 'Each priced combination has its own listing.' : 'Use single specifications and price. Saved variants are kept.'}</span></label>;
}
export function LaptopVariantBuilder({ laptop, settings, onChange }: { laptop: Laptop; settings?: RmbPricingSettings; onChange: (laptop: Laptop) => void }) {
  const [pendingRemoval, setPendingRemoval] = useState<{ property: 'cpus' | 'ram' | 'storage'; id: string; used: number } | null>(null);
  const config = laptop.variantConfig || emptyLaptopVariants();
  const set = (patch: Partial<LaptopVariantConfig>) => onChange({ ...laptop, variantConfig: { ...config, ...patch } });
  const preorder = isPreorderLaptop(laptop), priceKey = preorder ? 'priceRmb' : 'priceGhs';
  const applyRemoval = (property: 'cpus' | 'ram' | 'storage', id: string) => {
    const field = property === 'cpus' ? 'cpuId' : property === 'ram' ? 'ramId' : 'storageId';
    set({ [property]: config[property].filter(value => value.id !== id), rows: config.rows.filter(row => row[field] !== id) });
    setPendingRemoval(null);
  };
  const removeValue = (property: 'cpus' | 'ram' | 'storage', id: string) => {
    const field = property === 'cpus' ? 'cpuId' : property === 'ram' ? 'ramId' : 'storageId';
    const used = config.rows.filter(row => row[field] === id).length;
    if (used) setPendingRemoval({ property, id, used }); else applyRemoval(property, id);
  };
  return <section className="min-w-0 space-y-4 rounded-xl border border-[#cbdcd9] bg-[#f8fbfa] p-4">
    <h4 className="font-black text-[#014040]">Laptop variants</h4>
    {pendingRemoval && <div role="alertdialog" aria-label="Remove variant value" className="sticky top-4 z-20 space-y-3 rounded-xl border border-amber-300 bg-amber-50 p-4 shadow-lg"><p className="text-sm font-bold text-amber-900">This value is used by {pendingRemoval.used} combination(s). Removing it will also delete those combinations.</p><div className="flex flex-wrap gap-2"><button type="button" className={button} onClick={() => setPendingRemoval(null)}>Keep value</button><button type="button" className="rounded-xl bg-rose-700 px-3 py-2 text-xs font-bold text-white" onClick={() => applyRemoval(pendingRemoval.property, pendingRemoval.id)}>Remove value and combinations</button></div></div>}
    <div className="grid min-w-0 gap-4 lg:grid-cols-3">{(['cpus', 'ram', 'storage'] as const).map(property => <section key={property} className="min-w-0 space-y-2 rounded-xl border bg-white p-3"><h5 className="font-bold">{property === 'cpus' ? 'CPU' : property === 'ram' ? 'RAM' : 'Storage'}</h5>{config[property].map(value => <div key={value.id} className="min-w-0 space-y-2 rounded-lg border p-2">{'prefix' in value ? <div className="grid min-w-0 gap-2"><label className="text-xs">Prefix<input className={input} value={value.prefix} onChange={e => set({ cpus: config.cpus.map(v => v.id === value.id ? { ...v, prefix: e.target.value } : v) })} /></label><label className="text-xs">Model<input className={input} value={value.model} onChange={e => set({ cpus: config.cpus.map(v => v.id === value.id ? { ...v, model: e.target.value } : v) })} /></label></div> : <label className="block text-xs">Value<input className={input} value={value.value} onChange={e => set({ [property]: config[property].map(v => v.id === value.id ? { ...v, value: e.target.value } : v) })} /></label>}<button type="button" className={button} onClick={() => removeValue(property, value.id)}>Remove value</button></div>)}<button type="button" className={button} onClick={() => set(property === 'cpus' ? { cpus: [...config.cpus, { id: crypto.randomUUID(), prefix: '', model: '' }] } : { [property]: [...config[property], { id: crypto.randomUUID(), value: '' }] })}>+ Add variant</button></section>)}</div>
    <p className="text-xs text-slate-600">Add combinations manually. {preorder ? 'Enter RMB costs; the common shipping fees below apply to every combination.' : 'GHS prices are final selling prices, without additional charges.'} Changing Availability keeps both currencies; fill any missing prices before saving.</p>
    {config.rows.some(row => !row[priceKey] || row[priceKey]! <= 0) && <p role="alert" className="rounded-xl bg-amber-50 p-3 text-xs font-bold text-amber-800">Enter a {preorder ? 'RMB' : 'GHS'} price for every combination before saving. The other currency’s saved prices are kept.</p>}
    <div className="hidden grid-cols-4 gap-3 px-3 text-xs font-black min-[641px]:grid"><span>CPU</span><span>RAM</span><span>Storage</span><span>Price ({preorder ? 'RMB' : 'GHS'})</span></div>
    {config.rows.map((row, index) => <div key={row.id} className="grid min-w-0 gap-4 rounded-xl border bg-white p-3 min-[641px]:grid-cols-4">{(['cpuId', 'ramId', 'storageId'] as const).map((field, column) => <div key={field} className="min-w-0"><p className="mb-2 text-xs font-bold min-[641px]:hidden">{['CPU', 'RAM', 'Storage'][column]}</p><div className="flex min-w-0 flex-wrap gap-2 text-xs">{(field === 'cpuId' ? config.cpus.map(v => ({ id: v.id, label: cpuLabel(v) })) : config[field === 'ramId' ? 'ram' : 'storage'].map(v => ({ id: v.id, label: v.value }))).map(value => <LaptopVariantChip key={value.id} selected={row[field] === value.id} onClick={() => set({ rows: config.rows.map(v => v.id === row.id ? { ...v, [field]: value.id } : v) })}>{value.label || 'Empty value'}</LaptopVariantChip>)}</div></div>)}<div className="min-w-0 space-y-2"><label className="text-xs font-bold">Price ({preorder ? 'RMB' : 'GHS'})<input aria-label={`Combination ${index + 1} price ${preorder ? 'RMB' : 'GHS'}`} className={input} type="number" min="0.01" step="0.01" value={row[priceKey] ?? ''} onChange={e => set({ rows: config.rows.map(v => v.id === row.id ? { ...v, [priceKey]: e.target.value === '' ? undefined : Number(e.target.value) } : v) })} /></label>{!preorder && <p aria-live="polite" className="text-xs font-bold text-[#014040]">Final: {row.priceGhs && row.priceGhs > 0 ? formatPesewas(cedisToPesewas(row.priceGhs)) : 'Enter a price'}</p>}<button type="button" className={button} onClick={() => set({ rows: config.rows.filter(v => v.id !== row.id) })}>Delete combination</button></div>{preorder && <div className="min-w-0 min-[641px]:col-span-4"><p className="mb-2 text-xs font-bold">Combination {index + 1} · calculated prices for {laptopDeliveries(laptop).map(rmbDeliveryLabel).join(' / ')}</p><RmbCostEditor cost={{ ...laptop.preorderCost, rawCostRmb: row.priceRmb ?? 0 }} deliveries={laptopDeliveries(laptop)} settings={settings} readOnlyInputs onChange={() => {}} /></div>}</div>)}
    <button type="button" className={button} onClick={() => set({ rows: [...config.rows, { id: crypto.randomUUID(), cpuId: '', ramId: '', storageId: '' }] })}>+ Add combination</button>
    {preorder && <div className="grid gap-3 sm:grid-cols-2">{laptopDeliveries(laptop).map(delivery => { const key = delivery === 'express' ? 'shippingExpressGhs' : 'shippingTwoMonthsGhs'; return <label key={delivery} className="text-xs font-bold">Common shipping · {rmbDeliveryLabel(delivery)} (₵)<input className={input} type="number" min="0" step="0.01" value={laptop.preorderCost?.[key] ?? ''} onChange={e => onChange({ ...laptop, preorderCost: { ...laptop.preorderCost, rawCostRmb: laptop.preorderCost?.rawCostRmb ?? 0, [key]: e.target.value === '' ? undefined : Number(e.target.value) } })} /></label>; })}</div>}
  </section>;
}
